# Generated by Django 5.2.7 on 2025-11-02 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('request_path', models.CharField(max_length=255)),
                ('threat_detected', models.BooleanField(default=False)),
                ('blocked', models.BooleanField(default=False)),
            ],
        ),
    ]
